services:
  frontend:
    container_name: 'cheesus-frontend'
    build:
      context: .
      target: 'frontend'
    ports:
     - '4200:4200'
  backend:
    container_name: 'cheesus-api'
    build:
      context: .
      target: 'api'
    ports:
      - '3000:3000'
    env_file:
      - packages/api/.env
    environment:
      - DB_HOST=cheesus-db
  database:
    container_name: 'cheesus-db'
    image: postgres:16-alpine
    environment:
      # currently matching .env file in packages/api
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cheesus
    ports:
      - '5432:5432'